### ISSUE TITLE
about passthrough feature

### ISSUE THREAD

**Issue by kidach1** [Ayushanbhore/Unreal-Quest3-PassthroughSample#2]
> It demonstrates how to access and utilize real-time camera feed (passthrough), depth information, and mesh data to create AR experiences in the Unreal Engine environment for Oculus Quest 3.

Thank you for the interesting project. I saw the text above in your README, but I thought it wasn't possible to access the camera feed on Quest 3. Is there a way to do so?

Thanks.

**Comment by Ayushanbhore** [comment]
Hi kidach1,

We certainly cannot the access the camera feed on Quest 3 in this project for now because of API limitations and also because of Meta, but we can overlay it with interactable objects using spatial anchors or scene data. The updated Depth API will give us access to scene defined objects like a closet or a table only for it to act like an occuluder that will be used in certain Mixed Reality Apps. Hope this helps, Let me know if you have more questions :)

Thanks
Ayush

**Comment by kidach1** [comment]
I wish to apply some processing to the camera texture, so I hope it becomes possible to access it directly. Thank you!
